# Bugbot Configuration for beshr11 repositories
# This file configures automated issue triage, labeling, and assignment

# Issue labeling rules
labeling:
  # Auto-label based on title/keywords
  rules:
    - keywords: ["bug", "error", "crash", "broken", "fix"]
      labels: ["bug", "needs-triage"]
      severity: "medium"
    
    - keywords: ["feature", "enhancement", "improvement", "add"]
      labels: ["enhancement", "feature-request"]
      severity: "low"
    
    - keywords: ["security", "vulnerability", "exploit", "cve"]
      labels: ["security", "critical"]
      severity: "critical"
      priority: "high"
    
    - keywords: ["performance", "slow", "optimize", "speed"]
      labels: ["performance", "needs-investigation"]
      severity: "medium"
    
    - keywords: ["documentation", "docs", "readme", "guide"]
      labels: ["documentation"]
      severity: "low"
    
    - keywords: ["question", "help", "support", "how"]
      labels: ["question"]
      severity: "low"

  # Auto-assign based on file paths or labels
  assignment:
    # Assign based on file patterns
    paths:
      - pattern: "netlify/**/*"
        assignees: ["beshr11"]
      - pattern: "*.ts"
        assignees: ["beshr11"]
      - pattern: "*.tsx"
        assignees: ["beshr11"]
    
    # Assign based on labels
    labels:
      security:
        assignees: ["beshr11"]
      critical:
        assignees: ["beshr11"]

# Pull Request rules
pull_requests:
  # Required checks before merge
  required_checks:
    - "lint"
    - "test"
    - "build"
  
  # Auto-label PRs based on changes
  auto_label:
    - pattern: "*.test.ts"
      labels: ["test"]
    - pattern: "*.md"
      labels: ["documentation"]
    - pattern: "package.json"
      labels: ["dependencies"]
  
  # Comment templates
  comments:
    welcome: |
      ????? ??? ????????! ??
      ?????? ??? PR ??????.
      
      Thank you for your contribution! I'll review this PR soon.
    
    needs_changes: |
      ???? ????? ????????? ???????? ??? ?????.
      Please make the requested changes before merging.

# Issue templates
issue_templates:
  bug_report:
    title: "Bug Report"
    labels: ["bug", "needs-triage"]
    body: |
      ## Description
      ??? ???? ?????
      Clear description of the bug
      
      ## Steps to Reproduce
      1. 
      2. 
      3. 
      
      ## Expected Behavior
      ?? ??????? ?? ????
      What should happen
      
      ## Actual Behavior
      ?? ???? ??????
      What actually happens
      
      ## Environment
      - OS: 
      - Browser/Version: 
      - Node Version: 
      
      ## Additional Context
      ?? ??????? ??????
      Any additional information

  feature_request:
    title: "Feature Request"
    labels: ["enhancement", "feature-request"]
    body: |
      ## Description
      ??? ?????? ????????
      Description of the requested feature
      
      ## Use Case
      ????? ?????????
      Use cases
      
      ## Proposed Solution
      ???? ???????
      Proposed solution

# Response settings
responses:
  # Auto-respond to new issues
  auto_respond: true
  response_delay: "1h"  # Wait 1 hour before auto-response
  
  # Language preference
  language: "ar-SA"  # Arabic (Saudi) as primary, English as fallback

# Notification settings
notifications:
  # Notify on critical issues
  critical_issues: true
  # Notify on security issues
  security_issues: true
  # Notify on assignment
  assignment: true
